# This will run tests and move the issue into In Progress.

name: Print Context

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:    
      - main

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT