name: Move to In Progress when PR is Ready for Review

on:
  pull_request:
    types:
      - opened
    branches:    
      - main

jobs:
  ready-for-review-in-progress:
    runs-on: ubuntu-latest
    name: Move to In Progress Column
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Linked Issues Action
        uses: kin/gh-action-get-linked-issues@main
        id: linked-issues
        with:
          # Required: personal access token with permissions to archive cards
          access-token: "${{ secrets.GITHUB_TOKEN }}"
      - env:
          LINKED_ISSUES: ${{ steps.linked-issues.outputs.issues }}
        run: echo $LINKED_ISSUES
      - name: Move Issues to Ready for Review Column
        uses: kin/gh-action-move-issues-to-column@v1
        with:
          access-token: "${{ secrets.GITHUB_TOKEN }}"
          target-column: "Ready for Review"
          issues: ${{ steps.linked-issues.outputs.issues }}